### ISSUE TITLE
Patcher does not work?

### ISSUE THREAD

**Issue by Luckz** [Raphfrk/ServerPort#14]
I'm using 1.2_02 and a freshly downloaded and patched minecraft.jar won't autoconnect to the new server.

**Comment by Raphfrk** [comment]
Are you using Linux?  It seems Linux users have to do the patching manually.

Open the patcher.jar file

Open you minecraft,jar file

Copy all the files from /patched_files into the root of your minecraft.jar file.

Delete the meta-inf directory.

**Comment by Luckz** [comment]
No, I'm using Windows, but I'll try that.

**Comment by Luckz** [comment]
Still does not work!

**Comment by Raphfrk** [comment]
What happens when you are kicked?  What message is given?

Does the client crash or just give you the kick message?

**Comment by Luckz** [comment]
[Serverport] You have teleported, please connect to : <host>

**Comment by Raphfrk** [comment]
Is an IP address not give?

You need to type

/serverport globalhostname <hostname/ip of server>:<port>

Basically, you should type exactly what they player types in to connect.

**Comment by Luckz** [comment]
uhm, the github thing ate it because i enclosed it in brackets :D
it shows the right host.

**Comment by Raphfrk** [comment]
Are you sure you have the right file?

**Comment by Luckz** [comment]
Ok it actually worked now the manual way, making sure to follow your steps and downloading the newest patcher I could find here on github, but back in the day the patcher also succeeded at patching my game, now it only makes backups successfully.

**Comment by Raphfrk** [comment]
It should still work.  Is there any error?  It does do a version check now, but there should be a pop-up message if that fails.

**Comment by Luckz** [comment]
The problem was that the Patcher.jar was renamed to Patcher(5).jar by now in my download folder because I download it anew for every client patch.. and with those brackets it does not work.

**Comment by Raphfrk** [comment]
I thought I had fixed that.  It is supposed to pull from the actual file you run.
