### ISSUE TITLE
Invalid or corrupt jarfile craftbukkit-0.0.1-SNAPSHOT.jar

### ISSUE THREAD

**Issue by 411x** [Raphfrk/ServerPort#20]
"Invalid or corrupt jarfile craftbukkit-0.0.1-SNAPSHOT.jar"
I have this message when I try to execute this file:
http://prydwen.net/minec/latestsptwo/craftbukkit-0.0.1-SNAPSHOT.jar

Here is my command:
minecraft@omg:/home/minecraft/bukkit$ java -Xms4096M -Xmx4096M -jar craftbukkit-0.0.1-SNAPSHOT.jar nogui
Invalid or corrupt jarfile craftbukkit-0.0.1-SNAPSHOT.jar

The official craftbukkit version works fine.

Thanks !
Alix

**Comment by Raphfrk** [comment]
Those files are no longer in use.

You can just use the standard bukkit server.

**Comment by KAGamerAlex** [comment]
You might want to take it off the wiki then?
