### ISSUE TITLE
Request - Alteration of portal activation process

### ISSUE THREAD

**Issue by Khormin** [Raphfrk/ServerPort#24]
Would it be possible to make it possible to remove the sign once the portal has been activated?

Likewise, would it be possible to make it that the server portal will function regardless of materials, so long as there is viable block 90 portal 'material' in between?

**Comment by Khormin** [comment]
This would allow third-party portal creation mods (such as AncientGates or WormholeXtreme or similar) to function as cross-server portals as well.

The sign removal would be purely for ascetics =P

**Comment by Khormin** [comment]
NVM, turns out that this is covered in #9 - didn't see it on my look-through.

**Comment by Raphfrk** [comment]
I am not really adding new features any-more, the plugin is mostly getting a "keep working" level of support.

**Comment by Khormin** [comment]
No worries.

On 27/08/2011 10:24 PM, "Raphfrk" <
reply@reply.github.com>
wrote:
